### PR TITLE
Just trying to fix something

### PR DESCRIPTION
**Pull request by donsro**
Hope this will help to fix build issue. It works for me.

### CODE REVIEW

**Comment by donsro** [comment]
I think at least one approval has to be required to merge a new branch

**Review by patcoston — APPROVED** [review]
I like this!

**Comment by patcoston** [comment]
I tried to merge your fix but it says This pull request is still a work in progress
Draft pull requests cannot be merged.

**Comment by patcoston** [comment]
I merged. I'll pull and try it.

**Pull request merged**
